### ISSUE TITLE
Error al intentar generar un payment cobrando un fee con mercadopago connect => Invalid users involved

### ISSUE THREAD

**Issue by emanuelgomez** [mercadopago/code-examples#22]
Documentación seguida
- Mercadopago Connect: https://www.mercadopago.com.ar/developers/es/solutions/payments/custom-checkout/mercadopago-connect/
- Cobrar con tarjeta: https://www.mercadopago.com.ar/developers/es/solutions/payments/custom-checkout/charge-with-creditcard/javascript/
- Crear usuario test: https://www.mercadopago.com.ar/developers/en/solutions/payments/basic-checkout/test/test-users/
- Tarjetas de test: https://www.mercadopago.com.ar/developers/en/solutions/payments/basic-checkout/test/test-payments/

Libreria http utilizada
https://github.com/http-builder-ng/http-builder-ng

Precondiciones
- Mi aplicación esta activada como Marketplace/mercadopago connect
- Tanto mi aplicacion como mis usuarios estan en MLA
- No tengo las credenciales productivas activas, uso las PUBLIC y ACCESS_TOKEN de SANDBOX, las obtuve de https://www.mercadopago.com/mla/account/credentials 

1- Creo dos usuarios de test

```
MP mp = new MP(APPLICATION_ID, APPLICATION_SECRET)
String result = configure {
    request.contentType = 'application/json'
    request.uri.path = "https://api.mercadopago.com/users/test_user"
    request.uri.query = [access_token:mp.getAccessToken()]
    request.body = [site_id : 'MLA']
}.post()
```

Respuestas
```
{id=123456789, nickname=TESTUSR1, password=gatest1, site_status=active, email=test_user_1@testuser.com} //SELLER
{id=987654321, nickname=TESTUSR2, password=gatest2, site_status=active, email=test_user_2@testuser.com} //BUYER
```

2- Genero link de autorización para cada usuario, me autentico con cada uno y doy autorización a mi aplicación 
https://auth.mercadopago.com.ar/authorization?client_id=MY_APPLICATION_ID&response_type=code&platform_id=mp&redirect_uri=MY_REDIRECT_URI

3- El login y la autorización fue exitosa, Mercadopago llama a mi redirect_uri donde espero mis credenciales para almacenarlas.

```
Map<String,Object> body = [client_secret : SANDBOX_ACCESS_TOKEN,
                           grant_type: "authorization_code",
                           code: authorizationCode,
                           redirect_uri: MY_REDIRECT_URI]

def result = configure {
    request.uri = "https://api.mercadopago.com"
}.post {
    request.uri.path = "/oauth/token"
    request.accept = 'application/json'
    request.body = body
    request.contentType = 'application/x-www-form-urlencoded'
}
```

En cada uno de mis dos usuarios el formato de respuesta es el siguiente. Alamaceno esta información.
```

{
    "access_token": "USER_AT",
    "public_key": "USER_PK",
    "refresh_token": "USER_RT",
    "live_mode": false,
    "user_id": 123456789,
    "token_type": "bearer",
    "expires_in": 15768000,
    "scope": "offline_access read write"
}
```

4- Muestro a mi usuario el formulario tal y como lo sugiere la [documentación de cobrar con tarjeta](https://www.mercadopago.com.ar/developers/es/solutions/payments/custom-checkout/charge-with-creditcard/javascript/) y genero mi card token. Como estoy implementando mercadopago connect utilizo las PUBLICKEY de mi SELLER ya que estoy cobrando en su nombre, creo el cardToken utilizando la PUBLIC_KEY de mi test_user_1@testuser.com //SELLER. Desde mi frontend con mercadopago-sdk

```
Mercadopago.setPublishableKey(SELLER_PUBLIC_KEY)
Mercadopago.createToken(form, createCardTokenCallback)

```
Obtengo exitosamente mi cardToken con el siguiente formato.
```
{
    "id": "ff8080814cbd77a8014cc",
    "public_key": "TEST-3aea4333-9a45-882a-81jsd-b16d6fe9cfda",
    "card_id": null,
    "luhn_validation": true,
    "status": "active",
    "date_used": null,
    "card_number_length": 16,
    "date_created": "2015-04-16T13:06:25.525-04:00",
    "first_six_digits": "450995",
    "last_four_digits": "3704",
    "security_code_length": 3,
    "expiration_month": 6,
    "expiration_year": 2017,
    "date_last_updated": "2015-04-16T13:06:25.525-04:00",
    "date_due": "2015-04-24T13:06:25.531-04:00",
    "live_mode": false,
    "cardholder": {
        "identification": {
            "number": "23456789",
            "type": "type"
        },
        "name": "name"
    }
}
```

5- Envío mi CARDTOKEN a mi backend, ahi voy a utilizar el ACCESS_TOKEN de mi usuario test_user_1@testuser.com //SELLER  y el ID del CARDTOKEN

```
MP mp = new MP(SELLER_ACCESS_TOKEN) 
JSONObject payment = mp.post("/v1/payments", "{"+
			"'transaction_amount': 100,"+
			"'token': 'ff8080814cbd77a8014cc',"+ . //CARDTOKEN ID
			"'description': 'Title of what you are paying for',"+
			"'installments': 1,"+
			"'payer': {"+
				"'id': '12345678'"+
			"},"+
			"'payment_method_id': 'visa',"+
			"'application_fee': 2.56"+
		"}");

```
6- Obtengo el siguiente mensaje de error

```
{
    "message": "Invalid users involved",
    "error": "bad_request",
    "status": 400,
    "cause": [
        {
            "code": 2034,
            "description": "Invalid users involved",
            "data": null
        }
    ]
}

```
VARIANTES

Variante 1
En el paso 4 genero mi CARDTOKEN con el SANDBOX_PUBLICKEY de mi Aplicación . Mismo error

Variante 2
Utilizo las public key que aparecen en el siguiente link (https://www.mercadopago.com/mla/account/credentials) de mi usuario test_user_1@testuser.com //SELLER . Mismo error o invalid credentials, varia.

Gracias de antemano por cualquier aclaración/ayuda sobre como resolver el tema.

**Comment by hugodeaguiar** [comment]
Hi @emanuelgomez,

I needed to contact the MP, and I described that I was using the roles of inverted users. Make sure that the same is not happening to you.

I hope I have helped.

**Comment by emanuelgomez** [comment]
Hi @hugodeaguiar, thanks for your response

I had to create a third test_user, configure his application as Marketplace and authorize the other two test_users with this app. I was able to create a payment after this.
